---
# ECR Configuration
ecr_registry: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
ecr_repository: "backend-app"
ecr_tag: "latest"
aws_region: "us-east-1"

# Container Configuration
container_name: "backend-app"
host_port: 8080
container_port: 8080
restart_policy: "unless-stopped"
memory_limit: "1024m"

# Application Configuration
node_env: "production"

# User Configuration (from your variables.json)
backend_user: "{{ ansible.backend.backend_user | default('ubuntu') }}"
backend_config_file: "{{ ansible.backend.backend_config_file | default('backend_config.sh') }}"

# AWS Account ID (should be set as environment variable or group var)
aws_account_id: "{{ lookup('env', 'aws_account_id') | default('') }}"
