---
# These vars are loaded from your variables.json via group_vars/all.yml
# The json_vars structure is already loaded in all.yml

# User Configuration
backend_user: "{{ json_vars.ansible.backend.backend_user }}"
backend_config_file: "{{ json_vars.ansible.backend.backend_config_file }}"

# ECR Configuration (set via environment variables)
ecr_repository: "{{ lookup('env', 'ECR_REPO_BACKEND') | default('backend-app') }}"
ecr_tag: "{{ lookup('env', 'ecr_image_tag') | default('latest') }}"
aws_account_id: "{{ lookup('env', 'aws_account_id') }}"

# Container settings
container_name: "backend-container"
host_port: 8080
container_port: 8080
restart_policy: "unless-stopped"
memory_limit: "1024m"

# Application environment
node_env: "{{ json_vars.global.environment | default('production') }}"
