---
galaxy_info:
  author: "DevOps Team"
  description: "Deploy backend application from ECR using Docker"
  company: "Your Company"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - backend
    - ecr
    - aws
    - tomcat
    - java

dependencies: []
